### ISSUE TITLE
代码块显示行数，配置文件改了line_number也没用

### ISSUE THREAD

**Issue by PFISH1998** [invom/Material-T#12]
![image](https://user-images.githubusercontent.com/33245433/51785526-2455f400-2194-11e9-9988-9cb7b1a0c3c7.png)

**Comment by invom** [comment]
可以修改`Material-T\layout\_partial\footer.ejs`中以下位置
```js
<script>
$(window).on('load',function(){
   $('pre').addClass('prettyprint linenums');
   prettyPrint();
})
</script>
```
将其中的`linenums`删除。
但是没有行号的效果可能有点丑 🤣  下个版本会优化代码高亮。

**Comment by PFISH1998** [comment]
好的，主要是一列行号还行，出来三列

**Comment by invom** [comment]
不对呀，正常就是一列的

**Comment by PFISH1998** [comment]
你看我图片🤪

**Comment by PFISH1998** [comment]
我微信pengpengyu1998，加一下方便交流呗

**Comment by invom** [comment]
```yml
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:
```
这几项全部改为false，然后`hexo clean`,`hexo g`试试

**Comment by PFISH1998** [comment]
好像都试过了

**Comment by grcen** [comment]
到底改哪里？

**Comment by Alfxjx** [comment]
这个问题我也出现了，有解决办法吗

**Comment by invom** [comment]
@Alfxjx @grcen 
修改 **根目录** 下的 `_config.yml` ,不是主题的配置文件：
```yml
highlight:
  enable: false
  line_number: false
  auto_detect: false
```
这几项全部改 false，然后 `hexo clean`, `hexo g`
