### ISSUE TITLE
请取消打开新文章为新标签页的操作

### ISSUE THREAD

**Issue by BingshaNeko** [invom/Material-T#15]
请取消此功能或将此功能改成可选功能

**Comment by invom** [comment]
感谢建议，已设置为可选项。
```yml
index: 
  # available: _blank | _self
  post_url_target: _self
```
