### ISSUE TITLE
MarkDown的标题前面都自带一个#有考虑去掉吗

### ISSUE THREAD

**Issue by puzhicheng** [invom/Material-T#2]
我还一直以为是我markdown写的有问题

**Comment by invom** [comment]
你好 @puzhicheng ，设计`#`的本意是起到强调标题作用，所以暂时不会考虑在主分支中删除。
如果要去掉的话可以修改`source/css/post.styl`，删除其中的
```css
.post_content h1:before,h2:before,h3:before,h4:before,h5:before,h6:before{
    content: "# ";
    color: #0e5796;
}
```
